### ISSUE TITLE
Ability to override current page

### ISSUE THREAD

**Issue by ajreading** [castlegateit/cgit-wp-breadcrumb#1]
It would be very useful for nonstandard navigation if the crumbtrail plugin could accept a post ID to generate a crumbtrail for that specific post. It would also be beneficial to be able to generate a crumbtrail as a child of a given post ID.

For example. You have a structure such as "Home > Company > Team" where team is a page listing all team members. Your team posts are custom post types and so your crumbtrail does represent your structure. If you were able to generate a crumbtrail by specifying the template is a child of "Team" you'd be able to generate the correct crumbtrail for your team member pages even though they are a custom post type.

**Comment by johnkhughes** [comment]
I am going to close this as out of scope. We already have the breadcrumb nav menu plugin to work with custom nav structures and it is trivial to simply override the breadcrumb on particular page or template. It is also easier to code and easier to understand.
